"""Add sources field

Revision ID: 2dba838d16d8
Revises: 178e4299fe67
Create Date: 2025-06-10 16:48:43.218647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dba838d16d8'
down_revision: Union[str, None] = '178e4299fe67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('sources', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'sources')
    # ### end Alembic commands ###
